name: Lint

on:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  pre-commit:
    name: pre-commit-lite
    runs-on: rust
    steps:
      - uses: https://github.com/actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: https://github.com/Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2.8.2
      - uses: https://github.com/j178/prek-action@0bb87d7f00b0c99306c8bcb8b8beba1eb581c037 # v1.1.1
