name: Lint

on:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  pre-commit:
    name: pre-commit-lite
    runs-on: codeberg-small
    container:
      image: ghcr.io/catthehacker/ubuntu:rust-latest
    steps:
      - uses: https://github.com/actions/checkout@v6
      - uses: https://github.com/pre-commit-ci/lite-action@v1.1.0
        if: always()
        with:
          msg: apply code formatting
