name: Lint

on:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  pre-commit:
    name: pre-commit-lite
    runs-on: rust
    steps:
      - uses: https://github.com/actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: https://github.com/Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
      - uses: https://github.com/j178/prek-action@5337cb91e0fa35a7ff31b9ca345126d8bbbcdf16 # v2.0.6
