name: Test

on:
  push:
    branches: ["dev"]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: rust
    steps:
      - uses: https://github.com/actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: https://github.com/Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
