name: Upload to crates.io

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  deploy:
    name: Upload to crates.io
    runs-on: ubuntu-latest
    environment:
      name: crates.io
      url: https://crates.io/crates/rustpython-unparser
    steps:
      - uses: actions/checkout@v4
      - name: Publish
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
